# Spring
spring:
  application:
    name: saffron-server
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: always
# log
logging:
  level:
    root: error
    com.w.saffron: info
    com.xxl.job: error